### PR TITLE
chore: upgrade to Kotlin 1.8.10

### PR DESCRIPTION
**Pull request by celcius112**
Resolves https://github.com/ekino/spring-boot-starter-errors/issues/255

### CODE REVIEW

**Comment by clemstoquart** [comment]
IMO we should wait for the dokka 1.8 release.

**Comment by celcius112** [comment]
@clemstoquart i though it would not be that important since dokka does not seem to be used anywhere 😅

**Comment by clemstoquart** [comment]
It is used to generate documentation.

**Comment by clemstoquart** [comment]
Dokka 1.8.10 has been released.

**Pull request closed without merging**
